/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package hu.modeldriven.astah.traceability.ui;

/**
 * @author zsolt
 */
public class AbstractTraceabilityPanel extends javax.swing.JPanel {

    /**
     * Creates new form AbstractTraceabilityPanel
     */
    public AbstractTraceabilityPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbarPanel = new javax.swing.JPanel();
        modelElementLabel = new javax.swing.JLabel();
        modelElementTextField = new javax.swing.JTextField();
        selectButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        configureButton = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        toolbarPanel.setBackground(new java.awt.Color(255, 255, 255));
        toolbarPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        modelElementLabel.setText("Model element:");

        modelElementTextField.setEnabled(false);

        selectButton.setText("Select...");

        refreshButton.setText("Refresh");

        configureButton.setText("Configure...");

        javax.swing.GroupLayout toolbarPanelLayout = new javax.swing.GroupLayout(toolbarPanel);
        toolbarPanel.setLayout(toolbarPanelLayout);
        toolbarPanelLayout.setHorizontalGroup(
                toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(toolbarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(modelElementLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modelElementTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addComponent(configureButton)
                                .addContainerGap())
        );
        toolbarPanelLayout.setVerticalGroup(
                toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(toolbarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(modelElementLabel)
                                        .addComponent(modelElementTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(selectButton)
                                        .addComponent(refreshButton)
                                        .addComponent(configureButton))
                                .addContainerGap(12, Short.MAX_VALUE))
        );

        add(toolbarPanel, java.awt.BorderLayout.NORTH);

        scrollPanel.setPreferredSize(new java.awt.Dimension(600, 600));
        add(scrollPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton configureButton;
    private javax.swing.JLabel modelElementLabel;
    protected javax.swing.JTextField modelElementTextField;
    protected javax.swing.JButton refreshButton;
    protected javax.swing.JScrollPane scrollPanel;
    protected javax.swing.JButton selectButton;
    private javax.swing.JPanel toolbarPanel;
    // End of variables declaration//GEN-END:variables

}
